list: $/sitesforchurch/sitesforchurch/models/speaker/columns.yaml
modelClass: Sitesforchurch\Sitesforchurch\Models\Speaker
title: Speakers
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sitesforchurch/sitesforchurch/speakers/update/:id'
