list: $/sitesforchurch/sitesforchurch/models/welcomesection/columns.yaml
modelClass: Sitesforchurch\Sitesforchurch\Models\Welcomesection
title: Welcomesections
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sitesforchurch/sitesforchurch/welcomesections/update/:id'
