list: $/sitesforchurch/sitesforchurch/models/contactpage/columns.yaml
modelClass: Sitesforchurch\Sitesforchurch\Models\Contactpage
title: Contactpages
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sitesforchurch/sitesforchurch/contactpages/update/:id'
