list: $/sitesforchurch/sitesforchurch/models/belief/columns.yaml
modelClass: Sitesforchurch\Sitesforchurch\Models\Belief
title: Beliefs
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sitesforchurch/sitesforchurch/beliefs/update/:id'
