list: $/sitesforchurch/sitesforchurch/models/ministry/columns.yaml
modelClass: Sitesforchurch\Sitesforchurch\Models\Ministry
title: Ministries
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sitesforchurch/sitesforchurch/ministries/update/:id'
