list: $/sitesforchurch/sitesforchurch/models/aboutpage/columns.yaml
modelClass: Sitesforchurch\Sitesforchurch\Models\AboutPage
title: Otherpage
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sitesforchurch/sitesforchurch/otherpage/update/:id'
