list: $/sitesforchurch/sitesforchurch/models/leader/columns.yaml
modelClass: Sitesforchurch\Sitesforchurch\Models\Leader
title: Leadership
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sitesforchurch/sitesforchurch/leadership/update/:id'
